image: Visual Studio 2017

build_script:
  - dotnet pack src\14.0\ /p:versionprefix=14.0.${build} -v minimal
  - dotnet pack src\14.3\ /p:versionprefix=14.3.${build} -v minimal
  - dotnet pack src\15.0\ /p:versionprefix=15.0.${build} -v minimal
  - dotnet pack src\15.3\ /p:versionprefix=15.3.${build} -v minimal
  - dotnet pack src\15.6\ /p:versionprefix=15.6.${build} -v minimal
  - dotnet pack src\15.7\ /p:versionprefix=15.7.${build} -v minimal
  - dotnet pack src\15.8\ /p:versionprefix=15.8.${build} -v minimal

artifacts:
  - path: artifacts\*.nupkg
    name: NuGet package

deploy:
  - provider: NuGet
    artifact: /NuGet/
    api_key:
      secure: 6xBu/05BWJDPa2PRkxEH3PHU/caLvy2lzf1eWdRBGXwSCTejHtI+6e0V4s2LaVri
    on:
      branch: master
      appveyor_repo_commit_message_extended: /\[release\]/