image: Visual Studio 2017

build_script:
  - ps: dotnet pack "/p:BuildNumber=${env:APPVEYOR_BUILD_NUMBER}" -v minimal

artifacts:
  - path: artifacts\*.nupkg
    name: NuGet package

deploy:
  - provider: NuGet
    artifact: /NuGet/
    api_key:
      secure: 2LiTL6oY/0UkItVFZDP+iQqDsLl9BK9yM4rMyvbB9pL+/bXzzaerqFhR6NRmhRbs
    on:
      branch: master
      appveyor_repo_commit_message_extended: /\[release\]/
