image: Visual Studio 2017

build_script:
  - dotnet restore --verbosity quiet
  - dotnet pack src\Microsoft.VisualStudio.SDK.14.0.csproj
  - dotnet pack src\Microsoft.VisualStudio.SDK.15.0.csproj
  - dotnet pack src\Microsoft.VisualStudio.SDK.15.7.csproj

artifacts:
  - path: artifacts\*.nupkg
    name: NuGet package

deploy:
  - provider: NuGet
    artifact: /NuGet/
    api_key:
      secure: 6xBu/05BWJDPa2PRkxEH3PHU/caLvy2lzf1eWdRBGXwSCTejHtI+6e0V4s2LaVri
    on:
      branch: master
      appveyor_repo_commit_message_extended: /\[release\]/